apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: worker
  name: worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  template:
    metadata:
      labels:
        io.kompose.network/qunicorn-core-qunicorn: "true"
        io.kompose.service: worker
    spec:
      containers:
        - env:
            - name: BROKER_URL
              value: redis://broker:6379
            - name: CONTAINER_MODE
              value: worker
            - name: DB_URL
              value: postgresql://postgres:passwd@postgres/qunicorn
            - name: NUMBA_CACHE_DIR
              value: /app/cache
          image: iaasgeorgdl/qunicorn:release.11.23
          name: worker
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
